name: Mirroring 280blocker filters

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"

jobs:
  Mirroring:
    runs-on: ubuntu-latest

    steps:
      # Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v2

      # Download 280blocker filters
      - name: Download 280blocker filters
        run: |
          wget --no-check-certificate https://280blocker.net/files/280blocker_adblock_$(date "+%Y%m").txt -O 280blocker_adblock.txt
          wget --no-check-certificate https://280blocker.net/files/280blocker_1blocker_$(date "+%Y%m").1blockpkg -O 280blocker_1blocker.1blockpkg
          wget --no-check-certificate https://280blocker.net/files/280blocker_domain_$(date "+%Y%m").txt -O 280blocker_domain.txt
          wget --no-check-certificate https://280blocker.net/files/280blocker_domain_$(date "+%Y%m").zip -O 280blocker_domain.zip
          wget --no-check-certificate https://280blocker.net/files/280blocker_domain_ag_$(date "+%Y%m").txt -O 280blocker_domain_ag.txt

      # Push download filters
      - name: Push download filters
        uses: stefanzweifel/git-auto-commit-action@v4.7.1
        with:
          commit_message: ミラーを更新
